### ISSUE TITLE
How to define the hinge connection with clearance rightly in Siconos?

### ISSUE THREAD

**Issue by hunter1992** [siconos/siconos-tutorials#2]
I am very glad that Siconos can help me learn the theory of multi-body dynamics from the perspective of modeling and calculation, which makes me understand the theory better. After reading the Siconos documentation, I had a preliminary understanding of the Siconos computing process, but one thing that puzzled me was the establishment of interactions between components, called "Relations" in the Siconos documentation. More specifically, for example, if I need to build a pendulum,  which is connected to the ground by hinges, there is clearance in the hinges, as shown in the following picture:(In order to express the meaning, the gap in the picture is a little exaggerated)
![含间隙单摆](https://user-images.githubusercontent.com/16305873/65209884-f0856100-dacb-11e9-9a18-4d9f5de9f832.png)

Then, how can I define the relation rightly in Siconos? 
Thank you for your time！

**Comment by vacary** [comment]
You have several options for simulating this example in Siconos:

1)  the first option is to use siconos in C++ (or python) to create a simple example that uses only the kernel part of siconos. For that, you will have to write by yourself the constraints into your system. In your case, the signed distance between the tip of your bar and the circle where the tip must be constrained. Then you have to chose what type of dynamical model you want. You have two options:
    - `LagrangianDS` : in 2D, it should be simple to write the equation of motion of your bar at the center of mass parameterized for instance by q=[x, y , theta]. For that case, you can start from the `SimplePendulum.cpp` example in  /examples/mechanics/Pendulum` and then adapt the description of the constraints to write the `LagrangianRelation` .
    - `NewtonEulerDS` :  it is a 3d model of rigid body dynamics based on Newton-Euler equations. the parametrization of the motion is based on the positions of the center of mass and a orientation given by quaternion. The work to write the `Relation` in that case will be a bit more complicated but you will have a simulation of a 3D system. 
2) The second option is use the mechanics module of siconos with the bullet collision engine in python. You will just have to instanciate  2D or 3D body and to perform contact between the tip  of the bar as a small sphere and a cylinder. Be careful, because for the cylinder shape you will have to use a mesh since cylinder inside a cylinder in not implemented in bullet by default. You will find a lot of example like that in `/examples/mechanics/GeometricPrimitives/`
3) the third option which is perhaps the most complicated one but the most powerful is to use mechanics with the Opencascade detection collision tools as in the example in `/examples/mechanics/mechanisms/`

Let me now what you want to do and I can help you to write the example.

**Comment by hunter1992** [comment]
Thank you so much for your reply! @vacary  , The question closed because I pressed wrong button, and I have reopened it, excuse me.

Your reply is very helpful for me, it makes me relised that I have chance to solve the peoblem by using Kernal part and Mechanics part. 

Here is my calculation object, which is shown in the following picture, could be solved as 2D problem.

**Description of motion**: At the start, bar1 is in horizontal position(\phi_1 = 0), a constant force F (the direction is horizontal, point to left) push the slider moving to left, the \phi_1 is increasing, until to 90 degree, the bar1 hit the fixed block. 
**About the hinge connection**: There are 3 hinge totally, hingeA and hingeB are cylinder hinge, hingeC is sliding hinge. And the hingeA has clearance internal, the hingeB and hingeC are ideal hinge without clearance.
**The calculation aim**:
1. In the hingeA, during \phi_1 increasing from 0 degree to 90 degree, the impact force caused by clearance and the stick/slip after continuous contact;
2. When \phi_1 = 90 degree, there is collision between bar1 and the block which is fixed on the ground. The impact force of the collision need to be calculated.

_I thought the  2 aims above were solved in one file maybe too hard and complicated,  they can be apart into two problem, that's the reason I asked the single pendulum with clearance hinge at the beginning of this issue_.
![折叠翼展开机构示意图 - 副本](https://user-images.githubusercontent.com/16305873/65306237-86e28100-dbb7-11e9-9d17-cdb5a3d7ae38.gif)
I have build the smooth multibody dynamic model by Newton-Euler equation in O-x-y coordinate system:
![N-E](https://user-images.githubusercontent.com/16305873/65310408-d8dbd480-dbc0-11e9-8b1a-a905e9259277.jpg)
For the multibody system showed above:
The generalized coordinates:
![qdd](https://user-images.githubusercontent.com/16305873/65311352-bd71c900-dbc2-11e9-93ea-22895d0bb921.jpg)
h is the external force:
![h](https://user-images.githubusercontent.com/16305873/65311578-353ff380-dbc3-11e9-835c-d13039ddba4d.jpg)
M is the diagonal mass matrix:
![m](https://user-images.githubusercontent.com/16305873/65310856-c8782980-dbc1-11e9-9f23-295ddc4fca6a.jpg)
C is the geometrically constrained array, Cq is the jacobian matrix of C to q:
![C](https://user-images.githubusercontent.com/16305873/65312399-04f95480-dbc5-11e9-9c91-86c42b676edd.jpg)

I've been struggling for a couple of days, because the interactions about hingeA and the collision have not been established in the non-smooth dynamic parts.

Thanks for you help and reply so much, from installing to using Siconos, I have received your help several times, sincerely thank you @vacary

**Comment by hunter1992** [comment]
Here is some new progress about description the hinge internal clearance. As shown below:
![hinge clearance](https://user-images.githubusercontent.com/16305873/65381661-6c7be500-dd28-11e9-9b17-d2402d811aa0.jpg)

Using the hinge hole center O as coordinate origin, express the clearance as a function of \theta, the function name is C(\theta). 

Based on the Cosine theorem of triangle, we have:
![CodeCogsEqn](https://user-images.githubusercontent.com/16305873/65381763-042e0300-dd2a-11e9-99f1-8c60dfe7d896.gif)
Simplify the above formula and write r as a function of \theta:
![22](https://user-images.githubusercontent.com/16305873/65381790-933b1b00-dd2a-11e9-9317-9297e6ce3dc2.gif)
The clearance C(\theta):
![33](https://user-images.githubusercontent.com/16305873/65381813-207e6f80-dd2b-11e9-9892-e0941fe35ab2.gif)

now we need to add the relation above into the nonsoomth dynamical system, don't know how...

**Comment by vacary** [comment]
In the example, SimplePendulum.cpp, you have a directory called SimplePendulumPlugin 👍 
https://github.com/siconos/siconos-tutorials/tree/master/examples/mechanics/Pendulum/SimplePendulumPlugin

In this file, you will find a plugin that describes the dynamics of the pendulum and the the contraints with a vertical obstacle.

You have to replace the definition of this constraint by the equation you her just written above.

**Comment by hunter1992** [comment]
Thank you for telling me, I will go see it. @vacary
